/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * LumineStore API specification
 * OpenAPI spec version: 0.1.0
 */

export type ListProductsParams = {
  collectionId?: number;
  featured?: boolean;
  limit?: number;
};
