/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * LumineStore API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface Product {
  id: number;
  name: string;
  slug: string;
  description: string;
  shortDescription: string;
  price: number;
  comparePrice?: number | null;
  images: string[];
  collectionId?: number | null;
  collectionName?: string | null;
  featured: boolean;
  bestSeller: boolean;
  badge?: string | null;
  rating: number;
  reviewCount: number;
  inventory: number;
  tags: string[];
}

export interface Collection {
  id: number;
  name: string;
  slug: string;
  description: string;
  image: string;
  productCount: number;
}

export interface CartItem {
  id: number;
  productId: number;
  productName: string;
  productImage: string;
  price: number;
  quantity: number;
  lineTotal: number;
}

export interface Cart {
  sessionId: string;
  items: CartItem[];
  subtotal: number;
  total: number;
  itemCount: number;
}

export interface AddToCartRequest {
  sessionId: string;
  productId: number;
  quantity: number;
}

export interface UpdateCartItemRequest {
  sessionId: string;
  quantity: number;
}

export interface NewsletterSubscribeRequest {
  email: string;
}

export interface NewsletterSubscribeResponse {
  success: boolean;
  message: string;
}

export interface ErrorResponse {
  error: string;
}

export type ListProductsParams = {
  collectionId?: number;
  featured?: boolean;
  limit?: number;
};

export type GetCartParams = {
  sessionId: string;
};
