/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * LumineStore API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary List all products
 */
export const ListProductsQueryParams = zod.object({
  collectionId: zod.coerce.number().optional(),
  featured: zod.coerce.boolean().optional(),
  limit: zod.coerce.number().optional(),
});

export const ListProductsResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  slug: zod.string(),
  description: zod.string(),
  shortDescription: zod.string(),
  price: zod.number(),
  comparePrice: zod.number().nullish(),
  images: zod.array(zod.string()),
  collectionId: zod.number().nullish(),
  collectionName: zod.string().nullish(),
  featured: zod.boolean(),
  bestSeller: zod.boolean(),
  badge: zod.string().nullish(),
  rating: zod.number(),
  reviewCount: zod.number(),
  inventory: zod.number(),
  tags: zod.array(zod.string()),
});
export const ListProductsResponse = zod.array(ListProductsResponseItem);

/**
 * @summary Get a product by ID
 */
export const GetProductParams = zod.object({
  id: zod.coerce.number(),
});

export const GetProductResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  slug: zod.string(),
  description: zod.string(),
  shortDescription: zod.string(),
  price: zod.number(),
  comparePrice: zod.number().nullish(),
  images: zod.array(zod.string()),
  collectionId: zod.number().nullish(),
  collectionName: zod.string().nullish(),
  featured: zod.boolean(),
  bestSeller: zod.boolean(),
  badge: zod.string().nullish(),
  rating: zod.number(),
  reviewCount: zod.number(),
  inventory: zod.number(),
  tags: zod.array(zod.string()),
});

/**
 * @summary List all collections
 */
export const ListCollectionsResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  slug: zod.string(),
  description: zod.string(),
  image: zod.string(),
  productCount: zod.number(),
});
export const ListCollectionsResponse = zod.array(ListCollectionsResponseItem);

/**
 * @summary Get cart items
 */
export const GetCartQueryParams = zod.object({
  sessionId: zod.coerce.string(),
});

export const GetCartResponse = zod.object({
  sessionId: zod.string(),
  items: zod.array(
    zod.object({
      id: zod.number(),
      productId: zod.number(),
      productName: zod.string(),
      productImage: zod.string(),
      price: zod.number(),
      quantity: zod.number(),
      lineTotal: zod.number(),
    }),
  ),
  subtotal: zod.number(),
  total: zod.number(),
  itemCount: zod.number(),
});

/**
 * @summary Add item to cart
 */
export const AddToCartBody = zod.object({
  sessionId: zod.string(),
  productId: zod.number(),
  quantity: zod.number(),
});

export const AddToCartResponse = zod.object({
  sessionId: zod.string(),
  items: zod.array(
    zod.object({
      id: zod.number(),
      productId: zod.number(),
      productName: zod.string(),
      productImage: zod.string(),
      price: zod.number(),
      quantity: zod.number(),
      lineTotal: zod.number(),
    }),
  ),
  subtotal: zod.number(),
  total: zod.number(),
  itemCount: zod.number(),
});

/**
 * @summary Update cart item quantity
 */
export const UpdateCartItemParams = zod.object({
  cartItemId: zod.coerce.number(),
});

export const UpdateCartItemBody = zod.object({
  sessionId: zod.string(),
  quantity: zod.number(),
});

export const UpdateCartItemResponse = zod.object({
  sessionId: zod.string(),
  items: zod.array(
    zod.object({
      id: zod.number(),
      productId: zod.number(),
      productName: zod.string(),
      productImage: zod.string(),
      price: zod.number(),
      quantity: zod.number(),
      lineTotal: zod.number(),
    }),
  ),
  subtotal: zod.number(),
  total: zod.number(),
  itemCount: zod.number(),
});

/**
 * @summary Remove item from cart
 */
export const RemoveCartItemParams = zod.object({
  cartItemId: zod.coerce.number(),
});

export const RemoveCartItemResponse = zod.object({
  sessionId: zod.string(),
  items: zod.array(
    zod.object({
      id: zod.number(),
      productId: zod.number(),
      productName: zod.string(),
      productImage: zod.string(),
      price: zod.number(),
      quantity: zod.number(),
      lineTotal: zod.number(),
    }),
  ),
  subtotal: zod.number(),
  total: zod.number(),
  itemCount: zod.number(),
});

/**
 * @summary Subscribe to newsletter
 */
export const SubscribeNewsletterBody = zod.object({
  email: zod.string(),
});

export const SubscribeNewsletterResponse = zod.object({
  success: zod.boolean(),
  message: zod.string(),
});
